name: Export Supabase Schema and Data
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Login to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }} --debug
      
      - name: Link Supabase Project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --password ${{ secrets.SUPABASE_DB_PASSWORD }} --debug
      
      - name: Create db_schema directory
        run: mkdir -p db_schema
      
      - name: Export Schema
        run: |
          supabase db dump --db-url "postgresql://postgres.${{ secrets.SUPABASE_PROJECT_ID }}:${{ secrets.SUPABASE_DB_PASSWORD }}@${{ secrets.SUPABASE_DB_HOST }}:${{ secrets.SUPABASE_DB_PORT }}/${{ secrets.SUPABASE_DB_NAME }}" --debug > db_schema/schema.sql || echo "No schema to export yet"
      
      - name: Export Data Samples
        run: |
          supabase db dump --db-url "postgresql://postgres.${{ secrets.SUPABASE_PROJECT_ID }}:${{ secrets.SUPABASE_DB_PASSWORD }}@${{ secrets.SUPABASE_DB_HOST }}:${{ secrets.SUPABASE_DB_PORT }}/${{ secrets.SUPABASE_DB_NAME }}" --data-only --debug > db_schema/data_samples.sql || echo "No data to export yet"
      
      - name: Commit and Push Updates
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add db_schema/
          git commit -m "Auto-update Supabase schema and data samples" || echo "No changes"
          git push